### PR TITLE
Member initialization should be after the base class

### PR DESCRIPTION
**Pull request by HuaChunbo**

### CODE REVIEW

**Comment by JamesTerm** [comment]
This is a very interesting find.  I know some compilers are not concerned about the canonical order of the member initialization.  Was this found by compiler warning, or was there a dependency initialization problem?

**Comment by jianjunz** [comment]
@HuaChunbo, could you please share your experience with @JamesTerm. Please also submit this change to `master`. `76` branch is merged to `master`.

**Comment by HuaChunbo** [comment]
Hi James, this is discovered during our internal code analysis, which should be refactored by standard C++ rules. Thanks

**Comment by JamesTerm** [comment]
Ah ok, I see now.  Thanks for reply.

**Pull request merged**
