### PR TITLE
D3D11 decoder supports getting side data from HEVC streams.

### PR DESCRIPTION
**Pull request by jianjunz**
The implementation is picked from MSDK video decoder.

### CODE REVIEW

**Comment by dvrogozh** [comment]
@tannervoas742 : fyi

**Review by taste1981 — DISMISSED** [review]
Please make sure on encoding side this is already taken care of.

**Comment by jianjunz** [comment]
Encoding side is implemented here https://github.com/open-webrtc-toolkit/owt-client-native/blob/f1bf6862d5aa38c1f39ba72b2afbac3f22cc7376/talk/owt/sdk/base/customizedvideoencoderproxy.cc#L193-L242.

**Comment by tannervoas742** [comment]
@jianjunz was this code validated on your end? Picked this change up in WCG but still seeing no side data being received on client side for HEVC.

**Comment by jianjunz** [comment]
Only receiver side is validated by running Windows client with sample server. Tried both H.264 and HEVC, GetSideData is called, and codec was correctly detected.

**Comment by tannervoas742** [comment]
> Only receiver side was validated by running Windows client with sample server. Tried both H.264 and HEVC, GetSideData was called, and codec was correctly detected.

Okay as long as this has been validated I think its fine to merge. It is not solving the issue WCG is having but I will continue looking into this on our end.

**Comment by jianjunz** [comment]
I'll feed some random side data at sender side to see if it can be received before merging.

**Review by taste1981 — APPROVED** [review]

**Comment by tannervoas742** [comment]
Rebuilding and testing this with WCG. ETA ~2 hours

**Review by tannervoas742 — APPROVED** [review]
The latest version of this change works for WCG. HEVC side data is now present.

**Comment by jianjunz** [comment]
Thanks for your feedback. We're working on recovering CI for Windows and iOS.

**Pull request merged**
